version: "3"
services:
  nasa_graphql_api:
    build:
      context: .
    container_name: nasa_graphql_api
    networks:
      - graphql-network
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: postgres
    container_name: db
    restart: always
    env_file:
      - .env
    networks:
      - graphql-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prisma-postgres-api:
    build:
      context: .
    container_name: prisma-postgres-api
    networks:
      - graphql-network
    command: npx prisma migrate deploy
    depends_on:
      - db
      - nasa_graphql_api
volumes:
  postgres_data:

networks:
  graphql-network:
    driver: bridge
    name: graphql-network
